name: Yash GSI Maker
 
on: push

env:
  TYPE: build
  TZ: Asia/Manila
jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
     # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - uses: rokibhasansagar/slimhub_actions@main

         
       - name: Initializing environment
         continue-on-error: true
         timeout-minutes: 100
         run: |
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison ccache openjdk-8-jdk expect aria2
              git config --global user.email ${GitHubMail}
              git config --global user.name ${GitHubName}
              git config --global credential.helper store
              echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
              git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GSI_REPO }} source
              curl -sL https://git.io/file-transfer | sh

     
       - name: Setup Erfan Tools
         continue-on-error: true
         timeout-minutes: 10
         run: |
              mv ErfanGSIs2 ErfanGSIs
              sudo chmod -R 0777 ErfanGSIs
              sudo bash ErfanGSIs/setup.sh

       - name: Generate config.prop
         continue-on-error: true
         timeout-minutes: 3
         run: |
              java -jar GSIBot.jar
         
       - name: Add values
         continue-on-error: true
         timeout-minutes: 1
         run: |
             rm -rf configs/config.prop && rm -rf configs/sf-creds.config
             cd configs
             touch config.prop
             echo "#Bo³+t config file" >> "config.prop"
             echo "#Fri Jun 26 06:08:12 UTC 2020" >> "config.prop"
             echo "bot-username=${{ secrets.BOTUN }}" >> "config.prop"
             echo "bot-token=${{ secrets.BOTKEY }}" >> "config.prop"
             echo "bot-master=${{ secrets.USERKEY }}" >> "config.prop"
             echo "bot-submaster=${{ secrets.SUBKEY }}" >> "config.prop"
             touch sf-creds.config
             echo "#Config file" >> "sf-creds.config"
             echo "#Sun Nov 08 09:30:49 PST 2020" >> "sf-creds.config"
             echo "bot-sf-user=${{ secrets.SFUSER }}" >> "sf-creds.config"
             echo "bot-send-announcement=true" >> "sf-creds.config"
             echo "bot-sf-proj=${{ secrets.PROJECT }}" >> "sf-creds.config"
             echo "bot-announcement-id=-1001427383040" >> "sf-creds.config"
             echo "bot-sf-pass=${{ secrets.SFPASS }}" >> "sf-creds.config"
             echo "bot-sf-host=frs.sourceforge.net" >> "sf-creds.config"
       - name: Run Bot
         continue-on-error: true
         timeout-minutes: 350
         run: |
              sudo chmod -R 0777 *
              sudo java -jar GSIBot.jar
         
       - name: +1 
         continue-on-error: true
         timeout-minutes: 1
         run: |
              mkdir loop
              git clone https://github.com/yashlearnpython/gsibot-personal loop/loop
              cd loop/loop
              echo "1" >> loop.txt
              git add .
              git commit -m "Loop workflow"
              
       - name: Loop
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd loop/loop
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"master -> master\"
              set timeout -10
              interact"
